---
- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  vars:
    data: []  
    insecure: 'yes'
  vars_files:
    - ./vars.yaml
    - ./creds.yaml
  roles:
  - role: virtual-machine
  collections:
    - ovirt
  tasks:
    - name: Log out oVirt Engine
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
